### PR TITLE
Adding HexGender and Hex Sky

### PR DESCRIPTION
**Pull request by TechTastic**
I added [HexGender](https://modrinth.com/mod/hexgender) and [Hexxy Skies](https://modrinth.com/mod/hexsky) to the `hexaddons.json` file

### CODE REVIEW

**Comment by SamsTheNerd** [comment]
Should have less stuff manually filled and just let it fetch from modrinth.

**Comment by SamsTheNerd** [comment]
Can just have the modrinth/cf links. Add a description if you want one different from the modrinth summary.

**Comment by TechTastic** [comment]
There

**Comment by SamsTheNerd** [comment]
Does the long name "Hexxy Skies (Hex Sky)" look fine on the page btw ?

**Comment by TechTastic** [comment]
No idea honestly, if it doesn't then just take off the Hex Sky part

**Pull request merged**
